-- Basic Queries
--1. Display all users who joined after a specific date.
SELECT user_id, username, join_date
FROM users
WHERE join_date > '2022-12-31'
ORDER BY join_date;

--2. Find all games with a price greater than a certain amount.
SELECT game_id, title, price
FROM games
WHERE price > 24.99
ORDER BY price ASC;

--3. Display all games released between two dates.
SELECT title, release_date
FROM games
WHERE release_date BETWEEN '2013-01-01' AND '2017-12-31'
ORDER BY release_date ASC;

--4. Display all games published by a specific publisher.
SELECT title, pub.publisher_name
FROM games g
JOIN publishers pub
ON g.publisher_id = pub.publisher_id
WHERE publisher_name = 'Take-Two Interactive';

--5. Display all games developed by a specific developer.
SELECT title, dev.developer_name
FROM games g
JOIN developers dev
ON g.developer_id = dev.developer_id
WHERE developer_name = 'Capcom Dev 1';

--6. Show users who have a coin balance above the average balance.
SELECT user_id, username, coin_balance
FROM users
WHERE coin_balance > 994;

--7. The five games that have the lowest single review score.
SELECT title, MIN(rating) AS rating
FROM reviews r
JOIN games g
ON r.game_id = g.game_id
GROUP BY title
ORDER BY rating
LIMIT 5;

--8. Display users with lowest amount spent on games.
SELECT u.username, SUM(total_amount) AS total_spent
FROM orders o
JOIN users u
ON o.user_id = u.user_id
GROUP BY username
ORDER BY total_spent ASC
LIMIT 10;

--Intermediate Queries
--9. Display the total number of games owned by each user.
SELECT o.user_id, COUNT(oi.game_id) AS No_of_Games
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY user_id
ORDER BY user_id;

--10. Find the top 10 users with the largest game libraries.
SELECT o.user_id, COUNT(oi.game_id) AS No_of_Games
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY user_id
ORDER BY No_of_Games DESC
LIMIT 10;

--11. Show the total amount spent by every user.
SELECT user_id, SUM(total_amount) AS total_spent
FROM orders
GROUP BY user_id
ORDER BY user_id ASC;

--12. Find the highest spending users.
SELECT u.user_id, u.username, SUM(total_amount) AS Highest_Spent
FROM orders o
JOIN users u
ON o.user_id = u.user_id
GROUP BY u.user_id
ORDER BY SUM(total_amount) DESC
LIMIT 5;

--13. Calculate the average rating of each game.
SELECT g.game_id, title, ROUND(AVG(r.rating),1) AS avg_rating
FROM games g
JOIN reviews r
ON g.game_id = r.game_id
GROUP BY g.game_id
ORDER BY g.game_id;

--14. Find the highest-rated games.
SELECT g.game_id, g.title, ROUND(AVG(rating),1) AS highest_ratings
FROM reviews r
JOIN games g
ON r.game_id = g.game_id
GROUP BY g.game_id, g.title
ORDER BY highest_ratings DESC
LIMIT 5;

--15. Show the total revenue generated by each game.
SELECT game_id, SUM(price) AS revenue_generated
FROM order_items
GROUP BY game_id
ORDER BY game_id;

--16. Find the top 5 highest revenue-generating games.
SELECT game_id, SUM(price) AS revenue_generated
FROM order_items
GROUP BY game_id
ORDER BY revenue_generated DESC
LIMIT 5;

--17. Count the number of reviews written by each user.
SELECT user_id, COUNT(comment) AS No_of_reviews
FROM reviews
GROUP BY user_id
ORDER BY user_id;

--18. Show the users with the highest number of achievements.
SELECT user_id, COUNT(achievement_id) AS no_of_achievements
FROM user_achievements
GROUP BY user_id
ORDER BY no_of_achievements DESC
LIMIT 5;

--19. Display the total coins earned by each user.
SELECT ct.user_id, u.username, SUM(ct.coins)
FROM coin_transactions ct
JOIN users u
ON ct.user_id = u.user_id
GROUP BY ct.user_id, u.username
ORDER BY ct.user_id;

--20. Find the users with the highest current coin balance.
SELECT user_id, username, coin_balance AS current_balance
FROM users
ORDER BY coin_balance DESC
LIMIT 5;

--Advanced Queries
--21. Find games that have many wishlists but low sales.
SELECT w.game_id, wishlist_count, no_of_sale
FROM (
	SELECT game_id, COUNT(game_id) AS wishlist_count
		FROM wishlist
		GROUP BY game_id
) AS w
JOIN (
	SELECT game_id, COUNT(order_id) AS no_of_sale
		FROM order_items
		GROUP BY game_id
		ORDER BY game_id
) AS s
ON w.game_id = s.game_id
WHERE wishlist_count > no_of_sale;

--22. Show users whose game library size is above the average user.
SELECT user_id, games_owned
FROM (
    SELECT user_id, COUNT(game_id) AS games_owned
    FROM user_library
    GROUP BY user_id
) AS c
WHERE games_owned > (
    SELECT AVG(games_owned)
    FROM (
        SELECT user_id, COUNT(game_id) AS games_owned
        FROM user_library
        GROUP BY user_id
    ) AS avg_table
);

--23. Find games with ratings higher than the platform-wide average.
SELECT game_id, ratings
FROM (
	SELECT game_id, ROUND(AVG(rating),1) AS ratings
	FROM reviews
	GROUP BY game_id
) AS r
WHERE ratings < (
	SELECT AVG(c.avg_ratings)
	FROM (
		SELECT game_id, ROUND(AVG(rating),1) AS avg_ratings
		FROM reviews
		GROUP BY game_id
	) AS c
);